#!/bin/bash

# Grafana Access Guide
# Generated: $(date)

echo "========================================"
echo "Grafana Deployment - Quick Access Guide"
echo "========================================"
echo ""

# Get Grafana URL
GRAFANA_URL=$(kubectl get svc -n mlops grafana -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

echo "Grafana URL:"
echo "  http://${GRAFANA_URL}:3000"
echo ""
echo "Login Credentials:"
echo "  Username: admin"
echo "  Password: admin123"
echo ""
echo "========================================"
echo "Next Steps:"
echo "========================================"
echo ""
echo "1. Open Grafana in your browser:"
echo "   http://${GRAFANA_URL}:3000"
echo ""
echo "2. Login with admin/admin123"
echo ""
echo "3. Verify Prometheus data source:"
echo "   Configuration → Data Sources → Prometheus"
echo "   Should show: http://prometheus.mlops.svc.cluster.local:9090"
echo ""
echo "4. Import the dashboard:"
echo "   + (Create) → Import → Upload JSON file"
echo "   File: deployment/grafana-dashboard.json"
echo ""
echo "5. View your dashboard:"
echo "   Dashboards → Cat/Dogs Classifier API Monitoring"
echo ""
echo "========================================"
echo "Generate Test Traffic:"
echo "========================================"
echo ""
echo "API_URL=\"http://a464126408ba744778040079b625c9b4-1b7df649871d3e3b.elb.us-east-1.amazonaws.com\""
echo ""
echo "# Health checks"
echo "for i in {1..50}; do curl -s \$API_URL/health > /dev/null; sleep 0.5; done"
echo ""
echo "# Stats endpoint"
echo "for i in {1..20}; do curl -s \$API_URL/stats > /dev/null; sleep 1; done"
echo ""
echo "========================================"
echo "Useful Commands:"
echo "========================================"
echo ""
echo "# Check Grafana pod status"
echo "kubectl get pods -n mlops -l app=grafana"
echo ""
echo "# View Grafana logs"
echo "kubectl logs -n mlops deployment/grafana --tail=50"
echo ""
echo "# Port forward (access locally at http://localhost:3000)"
echo "kubectl port-forward -n mlops svc/grafana 3000:3000"
echo ""
echo "# Restart Grafana"
echo "kubectl rollout restart deployment/grafana -n mlops"
echo ""
echo "========================================"
