AWSTemplateFormation: '2010-09-09'
Description: 'CloudFormation template for MNIST Classifier EC2 deployment'

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

  GitHubUsername:
    Description: GitHub username for Container Registry access
    Type: String
    Default: aimlideas

  GitHubPAT:
    Description: GitHub Personal Access Token for Container Registry
    Type: String
    NoEcho: true
    Default: ''

  SSHLocation:
    Description: The IP address range that can SSH to the EC2 instances
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c02fb55b47d6bc99  # Amazon Linux 2023
    us-west-2:
      AMI: ami-0735c191cf914754d
    eu-west-1:
      AMI: ami-0d71ea30463e0ff8d

Resources:
  MNISTSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: mnist-classifier-sg
      GroupDescription: Security group for MNIST classifier
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP traffic
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
          Description: Allow SSH access
      Tags:
        - Key: Name
          Value: mnist-classifier-sg
        - Key: Application
          Value: MNIST-Classifier

  MNISTInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref MNISTSecurityGroup
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Set GitHub credentials
          export GITHUB_USERNAME='${GitHubUsername}'
          export GITHUB_PAT='${GitHubPAT}'
          
          # Update system
          yum update -y
          
          # Install Docker
          yum install -y docker
          systemctl start docker
          systemctl enable docker
          usermod -a -G docker ec2-user
          
          # Install Docker Compose
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          
          # Create application directory
          mkdir -p /home/ec2-user/mnist-app
          cd /home/ec2-user/mnist-app
          
          # Create docker-compose.yml
          cat > docker-compose.yml <<'EOFCOMPOSE'
          version: '3.8'
          services:
            mnist-api:
              image: ghcr.io/aimlideas/mnist-classifier:latest
              container_name: mnist-classifier
              ports:
                - "80:8000"
              environment:
                - MODEL_PATH=/app/models/cat_dogs_cnn_model.pt
                - PYTHONUNBUFFERED=1
              restart: unless-stopped
              healthcheck:
                test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 40s
              logging:
                driver: "json-file"
                options:
                  max-size: "10m"
                  max-file: "3"
          EOFCOMPOSE
          
          # Login to GitHub Container Registry if PAT provided
          if [ ! -z "$GITHUB_PAT" ]; then
              echo "$GITHUB_PAT" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
          fi
          
          # Pull and start the application
          docker-compose pull
          docker-compose up -d
          
          # Set ownership
          chown -R ec2-user:ec2-user /home/ec2-user/mnist-app
          
          # Send success signal
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MNISTInstance --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: mnist-classifier-instance
        - Key: Application
          Value: MNIST-Classifier
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M

Outputs:
  InstanceId:
    Description: Instance ID of the MNIST classifier server
    Value: !Ref MNISTInstance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  PublicIP:
    Description: Public IP address of the MNIST classifier server
    Value: !GetAtt MNISTInstance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'

  ServiceURL:
    Description: URL of the MNIST classifier service
    Value: !Sub 'http://${MNISTInstance.PublicIp}'
    Export:
      Name: !Sub '${AWS::StackName}-ServiceURL'

  SSHCommand:
    Description: SSH command to connect to the instance
    Value: !Sub 'ssh -i ~/.ssh/${KeyName}.pem ec2-user@${MNISTInstance.PublicIp}'
    Export:
      Name: !Sub '${AWS::StackName}-SSHCommand'
