AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance for MNIST Classifier - Termination Protection DISABLED'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Instance Configuration"
        Parameters:
          - InstanceType
          - KeyName
          - VolumeSize
      - Label:
          default: "Network Configuration"
        Parameters:
          - VPCStackName
          - SSHLocation
      - Label:
          default: "Application Configuration"
        Parameters:
          - GitHubUsername
          - GitHubPAT
          - DockerImage
      - Label:
          default: "Tags"
        Parameters:
          - Environment
          - Project

Parameters:
  Environment:
    Description: Environment name
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development

  Project:
    Description: Project name
    Type: String
    Default: mlops-mnist

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t2.micro
      - t2.small
      - t2.medium

  KeyName:
    Description: EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

  VolumeSize:
    Description: EBS Volume size in GB
    Type: Number
    Default: 30
    MinValue: 20
    MaxValue: 100

  VPCStackName:
    Description: Name of VPC CloudFormation stack (leave empty to create new security group)
    Type: String
    Default: ''

  SSHLocation:
    Description: IP range for SSH access
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})

  GitHubUsername:
    Description: GitHub username for GHCR
    Type: String
    Default: aimlideas

  GitHubPAT:
    Description: GitHub Personal Access Token
    Type: String
    NoEcho: true
    Default: ''

  DockerImage:
    Description: Docker image to deploy
    Type: String
    Default: ghcr.io/aimlideas/mlops-assignment2/cats-dogs-classifier:latest

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c02fb55b47d6bc99
    us-west-2:
      AMI: ami-0735c191cf914754d
    eu-west-1:
      AMI: ami-0d71ea30463e0ff8d
    ap-south-1:
      AMI: ami-0c2af51e265bd5e0e

Conditions:
  HasVPCStack: !Not [!Equals [!Ref VPCStackName, '']]

Resources:
  # Security Group
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Project}-ec2-sg-${Environment}'
      GroupDescription: Security group for MNIST classifier EC2 instance
      VpcId: !If
        - HasVPCStack
        - Fn::ImportValue: !Sub '${VPCStackName}-VPC-ID'
        - !Ref AWS::NoValue
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
          Description: Application API
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
          Description: SSH
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound
      Tags:
        - Key: Name
          Value: !Sub '${Project}-ec2-sg-${Environment}'
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: TerminationProtection
          Value: Disabled

  # IAM Role for EC2
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Project}-ec2-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${Project}-*'
                  - !Sub 'arn:aws:s3:::${Project}-*/*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ec2/${Project}/*'
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${Project}-ec2-profile-${Environment}'
      Roles:
        - !Ref EC2Role

  # EC2 Instance
  MNISTInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !If
        - HasVPCStack
        - Fn::ImportValue: !Sub '${VPCStackName}-PublicSubnet1-ID'
        - !Ref AWS::NoValue
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: gp3
            DeleteOnTermination: true
            Encrypted: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Logging
          exec > >(tee /var/log/user-data.log)
          exec 2>&1
          
          echo "=== Starting MNIST Classifier Setup ==="
          echo "Timestamp: $(date)"
          
          # Update system
          echo "Updating system packages..."
          yum update -y
          
          # Install Docker
          echo "Installing Docker..."
          yum install -y docker
          systemctl start docker
          systemctl enable docker
          usermod -a -G docker ec2-user
          
          # Install Docker Compose
          echo "Installing Docker Compose..."
          DOCKER_COMPOSE_VERSION="2.23.0"
          curl -L "https://github.com/docker/compose/releases/download/v${!DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
          
          # Install CloudWatch Agent
          echo "Installing CloudWatch Agent..."
          wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
          rpm -U ./amazon-cloudwatch-agent.rpm
          
          # Create application directory
          echo "Setting up application directory..."
          mkdir -p /home/ec2-user/mnist-app/{models,logs}
          cd /home/ec2-user/mnist-app
          
          # Create docker-compose.yml
          echo "Creating docker-compose configuration..."
          cat > docker-compose.yml <<'EOFCOMPOSE'
          version: '3.8'
          
          services:
            mnist-api:
              image: ${DockerImage}
              container_name: mnist-classifier
              ports:
                - "80:8000"
                - "8000:8000"
              environment:
                - MODEL_PATH=/app/models/cat_dogs_cnn_model.pt
                - PYTHONUNBUFFERED=1
                - LOG_LEVEL=INFO
              volumes:
                - ./logs:/app/logs
              restart: unless-stopped
              healthcheck:
                test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 40s
              logging:
                driver: "json-file"
                options:
                  max-size: "10m"
                  max-file: "5"
          EOFCOMPOSE
          
          # Login to GitHub Container Registry
          echo "Logging into GitHub Container Registry..."
          if [ ! -z "${GitHubPAT}" ]; then
              echo "${GitHubPAT}" | docker login ghcr.io -u "${GitHubUsername}" --password-stdin
          else
              echo "Warning: GitHub PAT not provided, using anonymous access"
          fi
          
          # Pull and start application
          echo "Pulling Docker image..."
          docker-compose pull
          
          echo "Starting application..."
          docker-compose up -d
          
          # Wait for application to be healthy
          echo "Waiting for application to be healthy..."
          for i in {1..30}; do
              if docker-compose ps | grep -q "healthy"; then
                  echo "Application is healthy!"
                  break
              fi
              echo "Waiting... attempt $i/30"
              sleep 10
          done
          
          # Set ownership
          chown -R ec2-user:ec2-user /home/ec2-user/mnist-app
          
          # Create a systemd service for auto-restart
          echo "Creating systemd service..."
          cat > /etc/systemd/system/mnist-classifier.service <<'EOFSVC'
          [Unit]
          Description=MNIST Classifier Docker Compose
          Requires=docker.service
          After=docker.service
          
          [Service]
          Type=oneshot
          RemainAfterExit=yes
          WorkingDirectory=/home/ec2-user/mnist-app
          ExecStart=/usr/local/bin/docker-compose up -d
          ExecStop=/usr/local/bin/docker-compose down
          
          [Install]
          WantedBy=multi-user.target
          EOFSVC
          
          systemctl daemon-reload
          systemctl enable mnist-classifier.service
          
          echo "=== Setup completed successfully ==="
          echo "Application URL: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):8000"
          
          # Signal CloudFormation
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MNISTInstance --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: !Sub '${Project}-instance-${Environment}'
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
        - Key: TerminationProtection
          Value: Disabled
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M

  # Elastic IP
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MNISTInstance
      Tags:
        - Key: Name
          Value: !Sub '${Project}-eip-${Environment}'
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MNISTInstance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  InstancePublicIP:
    Description: Public IP address
    Value: !Ref ElasticIP
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'

  InstancePrivateIP:
    Description: Private IP address
    Value: !GetAtt MNISTInstance.PrivateIp
    Export:
      Name: !Sub '${AWS::StackName}-PrivateIP'

  ServiceURL:
    Description: Application URL
    Value: !Sub 'http://${ElasticIP}:8000'
    Export:
      Name: !Sub '${AWS::StackName}-ServiceURL'

  HealthCheckURL:
    Description: Health check endpoint
    Value: !Sub 'http://${ElasticIP}:8000/health'

  SSHCommand:
    Description: SSH command
    Value: !Sub 'ssh -i ~/.ssh/${KeyName}.pem ec2-user@${ElasticIP}'

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'

  TerminationProtection:
    Description: Termination Protection Status
    Value: 'DISABLED - Stack can be deleted without additional steps'
